apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentcalci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calciapp
  template:
    metadata:
      labels:
        app: calciapp
    spec:
      containers:
      - name: calciappcontainer
        image: mycontainerregistry0103.azurecr.io/image01
